cask_args appdir: '/Applications'
tap 'caskroom/cask'
brew 'git'
brew 'vim'
brew 'rbenv'
brew 'pyenv'
brew 'mysql'
brew 'shellcheck'
brew 'nkf'
brew 'wget'
brew 'node'
brew 'hub'
brew 'awscli'
brew 'ansible'
brew 'heroku-toolbelt'
brew 'mas'

cask 'iterm2'
cask 'java'
cask 'dropbox'
brew 'docker'
cask 'vagrant'
brew 'docker'
cask 'google-japanese-ime'
cask 'google-chrome'
cask 'karabiner' # In case of MacOS Sierra, 'karabiner-elements'
cask 'slack'
cask 'atom'
cask 'clipy'
cask 'mysqlworkbench'
cask 'sqlworkbenchj'
cask 'sourcetree'
cask 'firefox'
cask 'jasper'
