tap 'caskroom/cask'

brew 'brew-cask'
brew 'git'
brew 'rbenv'
brew 'mysql'
brew 'vim'
brew 'nkf'
brew 'node'
brew 'hub'

cask 'iterm2'
cask 'dropbox'
cask 'virtualbox'
cask 'vagrant'
cask 'google-japanese-ime'
cask 'google-chrome'
cask 'karabiner'
cask 'slack'
cask 'atom'
cask 'catchmouse'
cask 'mysqlworkbench'
cask 'sourcetree'
cask 'firefox'
cask 'au-wifi-connect'
